# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

language:
  - cpp

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
# * http://stackoverflow.com/a/30925448/2288008
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3

      # python3-pip package is not available, use 'easy_install3':
      # * https://github.com/travis-ci/apt-package-whitelist/issues/768
      - python3-setuptools # easy_install3

      # https://github.com/travis-ci-tester/travis-test-clang-cxx-11
      - libstdc++-4.8-dev

      # https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
      - g++-4.8

      # For Qt
      - libegl1-mesa-dev

      # Packages for Android development: http://superuser.com/a/360398/252568
      - libncurses5:i386
      - libstdc++6:i386
      - zlib1g:i386

env:
  global:
    - secure: "IpVQQ3WaLQdSYtZTJFB+/1zJw1Jhli+AuKUfzikeO/EMv1QVD8sOAlsfGkrs/0V/uzLnq3yo8I8VjakGySZW7RquT7JlTF8jIrbvPGltMCL2AGlpmA9fsohXJ3jddWLD1jI9/GP53SZFpA3WHN8PSufbbtVx9snATiYH/c7nebuHz4xZ7uOV6zAIAfeCaqTjxC6NXAjp18bwOcMoSBGy94KmOQK7TqC0+bIFV62V0YXsp/0sC12n80X7mrV3d1K5GXH18akzOyl5/J2UtCsOt47591uu1VG8lfRiq3Hd1Q5zyfc0C74nVuYHUCT0ykT+3eWSO5LA3crY4NXzCXNxJ7tRX6rIT61V56YwSSMm8HgrtMkCplXMLHEtrZlmIVumgn20YUnSUP40Giaib/tv3cyaKPeF1Wv99nqJvd7qnmKl+TcrAiMtM1gGtyih2NgdUoc2ukJv8/Gx3pXQNlzZ2Wg4AEDZW6wHugxtUjFllwM8wmKKdARyLozudB6cfFjw4VBp2EH8xGnRG7RhjuC+XeFl3Z8iKs7TzRxZTosTRSC9SzxVBiPevi4CdVD48CzYpdReoxjhHqX+ZTDlpx0WZ1mmpYQz+dD4vHKl5iUX+SwEItqOIZiDpIw5jVbiiCtEUOI7UBMZHDoPAgHDx63HAKdvIkr5HC3yMoWeDQgy90c="

matrix:
  include:
    # qt-widgets {
    # Linux {
    - os: linux
      env: PROJECT_DIR=examples/qt-widgets TOOLCHAIN=clang-libstdcxx
    - os: linux
      env: PROJECT_DIR=examples/qt-widgets TOOLCHAIN=gcc-4-8
    - os: linux
      env: PROJECT_DIR=examples/qt-widgets TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    # }

    # OSX {
    - os: osx
      env: PROJECT_DIR=examples/qt-widgets TOOLCHAIN=libcxx
    - os: osx
      env: PROJECT_DIR=examples/qt-widgets TOOLCHAIN=osx-10-11
    - os: osx
      env: PROJECT_DIR=examples/qt-widgets TOOLCHAIN=ios-nocodesign-9-3-wo-armv7s
    - os: osx
      env: PROJECT_DIR=examples/qt-widgets TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    # }
    # }

    # qt-core {
    # OSX {
    - os: osx
      env: PROJECT_DIR=examples/qt-core TOOLCHAIN=osx-10-11
    # }
    # }

    # qt-camera {
    # Linux {
    - os: linux
      env: PROJECT_DIR=examples/qt-camera TOOLCHAIN=clang-libstdcxx
    - os: linux
      env: PROJECT_DIR=examples/qt-camera TOOLCHAIN=gcc-4-8
    - os: linux
      env: PROJECT_DIR=examples/qt-camera TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    # }

    # OSX {
    - os: osx
      env: PROJECT_DIR=examples/qt-camera TOOLCHAIN=libcxx
    - os: osx
      env: PROJECT_DIR=examples/qt-camera TOOLCHAIN=osx-10-11
    - os: osx
      env: PROJECT_DIR=examples/qt-camera TOOLCHAIN=ios-nocodesign-9-3-wo-armv7s
    - os: osx
      env: PROJECT_DIR=examples/qt-camera TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    # }
    # }

    # qt-location {
    # Linux {

    # FIXME:
    # In file included from sweep/cdt.cpp:31:
    # In file included from sweep/cdt.h:35:
    # In file included from sweep/advancing_front.h:35:
    # In file included from sweep/../common/shapes.h:39:
    # In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/cmath:44:
    # In file included from /usr/include/math.h:427:
    # /usr/include/x86_64-linux-gnu/bits/math-finite.h:177:1: error: unknown type name '__extern_always_inline'
    # __extern_always_inline double __NTH (lgamma (double __d))
    #
    # - os: linux
    #   env: PROJECT_DIR=examples/qt-location TOOLCHAIN=clang-libstdcxx

    - os: linux
      env: PROJECT_DIR=examples/qt-location TOOLCHAIN=gcc-4-8
    - os: linux
      env: PROJECT_DIR=examples/qt-location TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    # }

    # OSX {
    - os: osx
      env: PROJECT_DIR=examples/qt-location TOOLCHAIN=libcxx
    - os: osx
      env: PROJECT_DIR=examples/qt-location TOOLCHAIN=osx-10-11
    - os: osx
      env: PROJECT_DIR=examples/qt-location TOOLCHAIN=ios-nocodesign-9-3-wo-armv7s
    - os: osx
      env: PROJECT_DIR=examples/qt-location TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    # }
    # }

    # qt-qml {
    # Linux {
    - os: linux
      env: PROJECT_DIR=examples/qt-qml TOOLCHAIN=clang-libstdcxx
    - os: linux
      env: PROJECT_DIR=examples/qt-qml TOOLCHAIN=gcc-4-8
    - os: linux
      env: PROJECT_DIR=examples/qt-qml TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    # }

    # OSX {
    - os: osx
      env: PROJECT_DIR=examples/qt-qml TOOLCHAIN=libcxx
    - os: osx
      env: PROJECT_DIR=examples/qt-qml TOOLCHAIN=osx-10-11
    - os: osx
      env: PROJECT_DIR=examples/qt-qml TOOLCHAIN=ios-nocodesign-9-3-wo-armv7s
    - os: osx
      env: PROJECT_DIR=examples/qt-qml TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    # }
    # }

install:
  # Info about OS
  - uname -a

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install python3; fi

  # Install 'ant' for Android
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install ant; fi

  # Install Python package 'requests'
  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
  - if [[ "`uname`" == "Linux" ]]; then travis_retry easy_install3 --user requests==2.10.0; fi

  # Install latest Polly toolchains and scripts
  - wget https://github.com/ruslo/polly/archive/master.zip
  - unzip master.zip
  - POLLY_ROOT="`pwd`/polly-master"
  - export PATH="${POLLY_ROOT}/bin:${PATH}"

  # Install dependencies (CMake, Android NDK)
  - install-ci-dependencies.py

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:${PATH}"

  # Installed if toolchain is Android (otherwise directory doesn't exist)
  - export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"
  - export ANDROID_NDK_r11c="`pwd`/_ci/android-ndk-r11c"

script:
  - python3 ./jenkins.py

# https://docs.travis-ci.com/user/customizing-the-build/#Whitelisting-or-blacklisting-branches
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - pkg.template
